# 🚀 LocalAI Configuration
debug: true
log_level: debug
threads: 8
context_size: 2048

# Server settings
address: "0.0.0.0"
port: 8080

# Model directories
models_path: "/mnt/c/Users/tyler/~/LocalAI/models"
upload_limit: 20

# Features
cors: true
single_active_backend: false
parallel_requests: true

# Preload models
preload_models:
  - id: phi-2
    name: phi-2
    config: "/mnt/c/Users/tyler/~/LocalAI/config/phi2.yaml"
    
# Audio settings
audio:
  tts_enabled: true
  stt_enabled: true
  
# Image settings  
image:
  enabled: true
  path: "/mnt/c/Users/tyler/~/LocalAI/models/sd"
