apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lore-engine-hpa
  namespace: lore-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lore-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lore-engine-logs
  namespace: lore-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lore-engine-docs
  namespace: lore-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
